#!/bin/bash

# Render Deployment Readiness Check Script
# This script checks if your project is ready for Render deployment

echo "🚀 AjumaPlus CRM - Render Deployment Readiness Check"
echo "========================================================"
echo ""

# Color codes
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check functions
check_command() {
    if command -v $1 &> /dev/null; then
        echo -e "${GREEN}✅${NC} $1 is installed"
        return 0
    else
        echo -e "${RED}❌${NC} $1 is not installed"
        return 1
    fi
}

check_file() {
    if [ -f "$1" ]; then
        echo -e "${GREEN}✅${NC} $1 exists"
        return 0
    else
        echo -e "${RED}❌${NC} $1 is missing"
        return 1
    fi
}

check_directory() {
    if [ -d "$1" ]; then
        echo -e "${GREEN}✅${NC} $1 exists"
        return 0
    else
        echo -e "${RED}❌${NC} $1 is missing"
        return 1
    fi
}

# Start checks
echo "📋 Checking prerequisites..."
check_command "git"
check_command "node"
check_command "npm"

echo ""
echo "📁 Checking project structure..."
check_directory "backend"
check_directory "frontend"
check_directory "backend/src"
check_directory "frontend/src"
check_file "backend/package.json"
check_file "frontend/package.json"
check_file "backend/render.yaml"

echo ""
echo "📝 Checking configuration files..."
check_file "backend/.env.example"
check_file "frontend/.env.production"

echo ""
echo "🔧 Checking backend dependencies..."
if [ -d "backend/node_modules" ]; then
    echo -e "${GREEN}✅${NC} Backend dependencies installed"
else
    echo -e "${YELLOW}⚠️${NC} Backend dependencies not installed (will be installed during deployment)"
fi

echo ""
echo "🔧 Checking frontend dependencies..."
if [ -d "frontend/node_modules" ]; then
    echo -e "${GREEN}✅${NC} Frontend dependencies installed"
else
    echo -e "${YELLOW}⚠️${NC} Frontend dependencies not installed (will be installed during deployment)"
fi

echo ""
echo "🐳 Checking Docker configuration..."
check_file "docker-compose.yml"
check_file "backend/Dockerfile"
check_file "frontend/Dockerfile"

echo ""
echo "📊 Checking database configuration..."
if grep -q "DATABASE_URL" backend/.env.example 2>/dev/null; then
    echo -e "${GREEN}✅${NC} DATABASE_URL configuration found"
else
    echo -e "${YELLOW}⚠️${NC} DATABASE_URL not in .env.example (will be provided by Render)"
fi

echo ""
echo "🔒 Checking security configuration..."
if grep -q "JWT_SECRET" backend/.env.example 2>/dev/null; then
    echo -e "${GREEN}✅${NC} JWT_SECRET configuration found"
else
    echo -e "${YELLOW}⚠️${NC} JWT_SECRET not in .env.example (will be auto-generated by Render)"
fi

echo ""
echo "📧 Checking email configuration..."
if grep -q "SMTP" backend/.env.example 2>/dev/null; then
    echo -e "${GREEN}✅${NC} SMTP configuration found"
else
    echo -e "${YELLOW}⚠️${NC} SMTP configuration not found (email features may not work)"
fi

echo ""
echo "🤖 Checking AI configuration..."
if grep -q "OPENAI_API_KEY" backend/.env.example 2>/dev/null; then
    echo -e "${GREEN}✅${NC} OpenAI API configuration found"
else
    echo -e "${YELLOW}⚠️${NC} OpenAI API not configured (AI features will be disabled)"
fi

echo ""
echo "📚 Checking documentation..."
check_file "README.md"
check_file "RENDER_DEPLOYMENT_GUIDE.md"
check_file "SELF_HOSTING_GUIDE.md"

echo ""
echo "========================================================"
echo "📋 Deployment Readiness Summary"
echo "========================================================"

# Count issues
ISSUES=0

if ! command -v git &> /dev/null; then
    echo -e "${RED}❌${NC} Git is required for Render deployment"
    ISSUES=$((ISSUES+1))
fi

if ! command -v node &> /dev/null; then
    echo -e "${RED}❌${NC} Node.js is required for local testing"
    ISSUES=$((ISSUES+1))
fi

if [ ! -d "backend/src" ] || [ ! -d "frontend/src" ]; then
    echo -e "${RED}❌${NC} Source code directories are missing"
    ISSUES=$((ISSUES+1))
fi

if [ $ISSUES -eq 0 ]; then
    echo -e "${GREEN}✅${NC} Your project is ready for Render deployment!"
    echo ""
    echo "Next steps:"
    echo "1. Push code to GitHub"
    echo "2. Create Render account at render.com"
    echo "3. Follow RENDER_DEPLOYMENT_GUIDE.md"
    echo "4. Deploy PostgreSQL database"
    echo "5. Deploy backend service"
    echo "6. Deploy frontend to Vercel"
else
    echo -e "${RED}❌${NC} Found $ISSUES issue(s) that need to be resolved"
    echo ""
    echo "Please fix the issues above before deploying to Render"
fi

echo ""
echo "For detailed deployment instructions, see RENDER_DEPLOYMENT_GUIDE.md"
